language: ruby
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0

env:
  - "RAILS_VERSION=5.0.7"
  - "RAILS_VERSION=5.1.7"
  - "RAILS_VERSION=5.2.4"
  - "RAILS_VERSION=6.0.2"

matrix:
  exclude:
    - rvm: 2.4.9
      env: "RAILS_VERSION=6.0.2"

addons:
  code_climate:
    repo_token: 9b174f785a3f1ad8986730da28c2756320f0413067e7e06bad278280f47743fd

after_success:
  - bundle exec codeclimate-test-reporter
