language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0

env:
  - "RAILS_VERSION=5.2.5"
  - "RAILS_VERSION=6.0.3.6"
  - "RAILS_VERSION=6.1.3.1"
  - "RAILS_VERSION=main"

matrix:
  exclude:
    - rvm: 3.0.0
      env: "RAILS_VERSION=5.2.5"
    - rvm: 2.5.8
      env: "RAILS_VERSION=main"
    - rvm: 2.6.6
      env: "RAILS_VERSION=main"

addons:
  code_climate:
    repo_token: 9b174f785a3f1ad8986730da28c2756320f0413067e7e06bad278280f47743fd

script:
  - bundle exec rake build
  - bundle exec standardrb

after_success:
  - bundle exec codeclimate-test-reporter
